name: CI Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: Maks-korsh
          password: 123456

      - name: Build Docker images
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml build

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
